// <auto-generated />
using System;
using DashboardEmployee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashboardEmployee.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927125652_seedConfiguration")]
    partial class seedConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashboardEmployee.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Technology & Development"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("DashboardEmployee.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Email = "carlos.mendoza@company.se",
                            FullName = "Carlos Mendoza",
                            ImageUrl = "/images/avatar1.jpg",
                            Salary = 55000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            Email = "asa.oberg@company.se",
                            FullName = "Åsa Öberg",
                            ImageUrl = "/images/avatar2.jpg",
                            Salary = 48000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 1,
                            Email = "jose.martinez@company.se",
                            FullName = "José Martínez",
                            ImageUrl = "/images/avatar3.jpg",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 3,
                            Email = "linnea.sjoberg@company.se",
                            FullName = "Linnea Sjöberg",
                            ImageUrl = "/images/avatar4.jpg",
                            Salary = 51000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 1,
                            Email = "erik.lindqvist@company.se",
                            FullName = "Erik Lindqvist",
                            ImageUrl = "/images/avatar5.jpg",
                            Salary = 58500m
                        },
                        new
                        {
                            EmployeeId = 6,
                            DepartmentId = 3,
                            Email = "sofia.hernandez@company.se",
                            FullName = "Sofía Hernández",
                            ImageUrl = "/images/avatar6.jpg",
                            Salary = 46000m
                        });
                });

            modelBuilder.Entity("DashboardEmployee.Entities.Employee", b =>
                {
                    b.HasOne("DashboardEmployee.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DashboardEmployee.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
